return {
	DEBUG_MOCK = true,
	SUFFIX = "_DEVELOPMENT_01a",
	TEMPLATE = {
		-- Player Data Template:
		--[[ Example:
			```lua 
			Cash = 0,
			Stats = {
				Level = 1,
				Experience = 0,
			},
			```
		--]]
	},
	SESSION_END_MESSAGE = `Profile session ended. Please rejoin the game to continue playing.`,
	LOAD_FAILED_MESSAGE = `You've been kicked from the game. We had an issue loading your data. Please try again.`,
	MESSAGE = `You've been kicked from the game. We had an issue loading your data. Please try again.`,
}
