[package]
name = "luminalabsgames/characterguidearrow"
description = "Character guide arrow utility for Roblox"
version = "1.0.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
authors = ["LuminaLabsGames"]

[dependencies]
Trove = "sleitnick/trove@1.8.0"
Observers = "sleitnick/observers@0.4.0"

